### ISSUE TITLE
The rotation stops even though I keep pressing the button

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#23]
I keep pressing the z button, but the rotation stops. This will not happen when `--lockdown` is `infinite`. Is this an intentional behavior?

![tetris](https://user-images.githubusercontent.com/2453619/146027866-f506009f-3585-4934-8fca-3f326acbfb09.gif)

**Comment by ContentsViewer** [comment]
The reference says...

> Each time a rotation button is pressed, the Tetrimino in play rotates 90 degrees in the clockwise 
> or counterclockwise direction. Rotation can be performed while the Tetrimino is Auto-Repeating left or right. 
> **There is no Auto-Repeat for rotation itself.**
> (2009Tetris®Design Guideline, Section5.3 Rotation) 

so need to rotate ONCE by each pushing down key, not continue to rotate while pressing key.

**Comment by ko1nksm** [comment]
Oh, you're right. The correct implementation should not have auto-repeat. However, it seems difficult to do...
