### ISSUE TITLE
Unexpected error "Illegal instruction: 4" occurs in /bin/sh on macOS Big Sur

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#27]
I'm currently having trouble with this error. If this error occurs within `tetris`, the `lockdown_timer` will stop functioning. It may take some time for the error to occur.

I think this is probably an issue with macOS (Big Sur?). And I'm guessing it's an issue with `/bin/sh` (bash 3.2.57 with apple patches). So this is a report to share information. Do you have any information on this?

This is a small code that can be reproduced.

```sh
#!/bin/sh

set -eu

timer() {
  trap ':' USR1
  while kill -0 "$1"; do
    sleep 0.0001 &
    wait ||:
  done
  echo "timer end" >&2
}

reader() {
  while kill -0 "$1"; do
    sleep 0.1 # smaller values should be more likely to occur
    echo "reader 0"
  done
  echo "reader end" >&2
}

controller() {
  timer_pid="$1"
  echo "start [timer:$timer_pid]"
  while IFS= read -r line; do
    kill -USR1 "$timer_pid"
  done
}

timer "$$" & timer_pid=$!
reader "$$" | controller "$timer_pid" # line 31
```

```sh
$ sh tetris
start [timer:26583]
tetris: line 26: kill: (26583) - No such process
tetris: line 31: 26583 Illegal instruction: 4  timer "$$"
```

<details>
<summary>The issue does not occur in the original bash 3.2.57.</summary>

```console
$ docker run -it fidian/multishell
$ cat <<'HERE'>tetris
#!/bin/sh

set -eu

timer() {
  trap ':' USR1
  while kill -0 "$1"; do
    sleep 0.0001 &
    wait ||:
  done
  echo "timer end" >&2
}

reader() {
  while kill -0 "$1"; do
    sleep 0.1
    echo "reader 0"
  done
  echo "reader end" >&2
}

controller() {
  timer_pid="$1"
  echo "start [timer:$timer_pid]"
  while IFS= read -r line; do
    kill -USR1 "$timer_pid"
  done
}

timer "$$" & timer_pid=$!
reader "$$" | controller "$timer_pid" # line 31
HERE
$ bash-3.2.57 tetris
```

</details>

This Issue is only for sharing information and you are free to close it. If I can find a workaround, I'll suggesting it.

**Comment by ko1nksm** [comment]
I've reduced the reproducible code a bit. So far, I haven't found a workaround other than to stop background sleep. 😮‍💨

```sh
#!/bin/sh

set -eu

timer() {
  trap 'printf .' USR1
  while true; do
    sleep 0.01 &
    wait ||:
  done 
}

controller() {
  echo "start [timer:$1]"
  while true; do
    sleep 0.01
    kill -USR1 "$1"
  done
}

timer "$$" &
controller "$!"
```

**Comment by ko1nksm** [comment]
This seems to be a bug, and can be resolved by specifying the pid for the `wait`. See #28

```diff
--- tetris.old	2021-12-19 04:22:53.000000000 +0900
+++ tetris	2021-12-19 04:23:59.000000000 +0900
@@ -6,7 +6,7 @@
   trap 'printf .' USR1
   while true; do
     sleep 0.01 &
-    wait ||:
+    wait $! ||:
   done
 }
```

**Comment by ContentsViewer** [comment]
Thank you for your investigations.

This issue have not occurred yet in

* Free BSD 13
* Ubuntu 18.04. 20.04
* Solaris 11

( I dont have mac pc.... )

**Comment by ContentsViewer** [comment]
The differences between platforms due to bugs are troubling...

**Comment by ko1nksm** [comment]
I got this error again. It seems that it is not completely fixed. 😮‍💨

**Comment by ContentsViewer** [comment]
Oh my....

Are you using arm cpu?

**Comment by ko1nksm** [comment]
No, My Mac is MacBook Pro (Retina, 13-inch, Late 2013) Intel Core i5 2.4 GHz.

**Comment by ko1nksm** [comment]
Thanks!

**Comment by ko1nksm** [comment]
The issue seems to have been fixed!

<img width="558" src="https://user-images.githubusercontent.com/2453619/147113268-8f0b168f-4860-4549-96ed-fca76c0692d3.png">
