### ISSUE TITLE
Pause / Resume

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#39]
I think it would be useful to be able to pause and resume the game.

We need to hide the playfield while posing. The [Tetris guideline](https://tetris.fandom.com/wiki/Tetris_Guideline) says the following.

- Esc and F1 are to pause.
- Game must count down from 3 after you press start, and after you resume a paused game.

I create an Issue as you might want to implement this. I will contact you before I start the implementation.

**Comment by ContentsViewer** [comment]
YES.
This feature I have wanted.

**Comment by ContentsViewer** [comment]
Additionally the guideline says...

> 13.1.6 Pausing the Game
> Pressing the Pause button stops game play instantly and **hides** the Matrix, Next Queue, and 
> Hold Queue contents. The word “Pause” should be prominently displayed on screen. Pressing 
> the Pause button again resumes the game

**Comment by ko1nksm** [comment]
I am going to work on this next.
