### ISSUE TITLE
Allow replay without exiting the program after a game over

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#40]
I think it would be useful to be able to replay without exiting the program after a game over. This allows you to skip the display time of copyright.

I create an Issue as you might want to implement this. I will contact you before I start the implementation.

**Comment by ContentsViewer** [comment]
Yes. Thank you very much!

**Comment by ContentsViewer** [comment]
I'm trying to check the guideline and imitating the game followed by this guideline.

The games I often refer to are as follows (you know)

* Tetris 99
* [tetris.com](https://tetris.com/play-tetris)

**Comment by ContentsViewer** [comment]
Do you think it is needed to implement?
The current version starts up so fast that the players don't have to wait.

**Comment by ko1nksm** [comment]
#41 needs to measure the sleep runtime, so I think it might take longer on startup. (I was thinking of measuring the sleep runtime when the logo is displayed.)

However, I still don't know how #41 will turn out, and I might be able to measure it during "ready", so I think it's enough to think about it later.

Let's close it.
