### ISSUE TITLE
Optimizing the overhead of the sleep command

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#41]
As with any other command, there is an overhead in executing the sleep command.

```sh
# FALL_SPEED_LEVEL_15=0.007
$ time sh -c 'i=0; while [ $i -lt 1000 ]; do i=$((i+1)); sleep 0.007 > /dev/null; done'

real	0m11.345s
user	0m0.911s
sys	0m1.748s
```

I would like to eliminate this. I suspect that measuring the execution time of the sleep command will improve this issue. I don't know if this will work, but I am going to give it a try.

**Comment by ContentsViewer** [comment]
I impressed for your help. Very thanks!

**Comment by ContentsViewer** [comment]
I will implement the line clear effect and lockdown effect.

**Comment by ko1nksm** [comment]
I'm not sure how useful this feature will be, so I plan to implement an option to change the sleep method.

**Comment by ContentsViewer** [comment]
OK!

**Comment by ko1nksm** [comment]
I'm thinking of doing this in my own repository, so I'd like to close it from here. When it is done, I will create a PR as before. It may take some time.
