### ISSUE TITLE
Unexpected display of "Mini T-Spin"

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#42]
I may be mistaken, but I think it sometimes shows up as "Mini T-Spin" when I am not doing Mini T-Spin. I am not sure how to reproduce this.

**Comment by ContentsViewer** [comment]
Or `what_type_tspin()` function may be something wrong. I will re-check the logic.

**Comment by ko1nksm** [comment]
Sorry for the uncertainty. I'm not good enough at Tetris to be able to recreate the same situation at will. :-<

**Comment by ContentsViewer** [comment]
me too .......

**Comment by ko1nksm** [comment]
It seems to display even when I am not erasing lines, is this a specification?

**Comment by ContentsViewer** [comment]
Yes. The last action always shown. It will be redraw when new action occurs.

**Comment by ContentsViewer** [comment]
I've found a mistake. I'll fix it. Thank you.

**Comment by eggplants** [comment]
https://youtu.be/N3b0iVVjE6g?t=612
No line was erased. Is this tspin-mini? 
![sh-tetris testplay 10-13 screenshot](https://user-images.githubusercontent.com/42153744/147392609-d418824c-412b-44bc-9f49-1a3d8112b534.png)
![sh-tetris testplay 10-14 screenshot](https://user-images.githubusercontent.com/42153744/147392610-9f6dd55f-551b-4ef1-aad2-30b6927056ef.png)
![sh-tetris testplay 10-14 screenshot (1)](https://user-images.githubusercontent.com/42153744/147392612-e0d1f2ce-ea7b-450c-a8df-24701d67d9fb.png)

**Comment by ko1nksm** [comment]
@ContentsViewer
Thanks! I was surprised myself. I had not understood the rules correctly and was beginning to think it was a misunderstanding.

**Comment by eggplants** [comment]
https://harddrop.com/wiki/T-Spin
It seems to vary by implementation whether to adopt  line clear as a condition for the role of T-spin.

**Comment by eggplants** [comment]
>For a while, my understanding of t-spin minis was that they were t-spins that cleared one or no lines and were reached by a wall kick. This is how everyone tends to explain them, and it seems to be consistent with the kick/no kick problem in general. I could have sworn this was their explicit definition in at least one game, but now I am not so sure. Whatever the case may be, they are pretty darn weird now.

>To restate our conclusion, a t-spin is mini if
> - there is an open corner on the point-end,
> - it clears one line or less,
> - or reached its final (x,y) position by way of the t-spin triple wall kick

[What a T-Spin Mini is and why they are so confusing
](http://kitaru.1101b.com/tc/mini.html)

**Comment by eggplants** [comment]
From this text, it seems that the current implementation is fine!

**Comment by ko1nksm** [comment]
@ContentsViewer 
There seems to be a "Mini T-Spin double", but as far as I can tell from the source code, it is not defined.
https://harddrop.com/wiki/T-Spin_Mini_Double

@eggplants 
In my opinion, it is T-Spin (or Mini T-Spin) if the line is not erased, and T-Spin Single (TSS), T-Spin Double (TSD), or T-Spin Triple (TST) depending on the line erased.

**Comment by ContentsViewer** [comment]
@ko1nksm 

> There seems to be a "Mini T-Spin double", but as far as I can tell from the source code, it is not defined.
> https://harddrop.com/wiki/T-Spin_Mini_Double

In this case, this must be judged as **"Mini T-Spin Double"**.
I've reproduced it in another Tetris game (Tetris 99).
(I've not ever done and seen this case...)

I'll fix it.

Thank you very much!
