### ISSUE TITLE
Show "T-spin" on clear one or more lines

### ISSUE THREAD

**Issue by eggplants** [ContentsViewer/sh-tetris#50]
I think "T-spin" should be displayed when one or more lines are deleted.

**Comment by ko1nksm** [comment]
I thought so too, but it seems to be wrong.

https://www.youtube.com/watch?v=X_dGneUqi8I&t=8s

**Comment by eggplants** [comment]
Oh, sorry for my misunderstanding.

**Comment by eggplants** [comment]
How about this one?
https://github.com/ContentsViewer/sh-tetris/issues/42#issuecomment-1001066697
