### ISSUE TITLE
The swapped hold piece should be more visible

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#55]
<img  width="550" src="https://user-images.githubusercontent.com/2453619/147397877-70b4918f-5a04-46d7-af57-6fe112e10aa9.png">

<img  width="550" src="https://m.media-amazon.com/images/I/71judKYf8cL._AC_SL1280_.jpg">

**Comment by ContentsViewer** [comment]
This feature has been removed. It was difficult to get the same look in no-color mode.
