### ISSUE TITLE
v2.2.0 Release

### ISSUE THREAD

**Issue by ContentsViewer** [ContentsViewer/sh-tetris#56]
@ko1nksm @eggplants 

Hello!
Thank you for your kindness and contributions!

As you know, there are many changes and improvements from v2.1.0.

I'd like to freeze the features and release the next version (v2.2.0). (But still going to fix bugs and merge small changes.)

I'll plan to release between 2021-12-30 ~ 2022-01-03.

**Comment by ko1nksm** [comment]
@ContentsViewer

Before the release, I would like to contact you personally. I tried to contact you from [here](https://contentsviewer.work/Master/About/Contact), but I got an error message `{"error": "Invalid access."}`. Is there any other way to contact you?

**Comment by ko1nksm** [comment]
@ContentsViewer

Sorry, I was able to make an inquiry.

**Comment by ContentsViewer** [comment]
@eggplants 
I'd like to contact you. 
Can I send email to the address on your github profile page?

**Comment by eggplants** [comment]
@ContentsViewer Yes, you can.
