### ISSUE TITLE
High load on ksh93

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#64]
I noticed that the load was very high on ksh93. This is probably a bug related to local variables (`typeset`) in ksh93. This is not reproduced by [ksh93u+m](https://github.com/ksh93/ksh) and  ksh2020.

Note: ksh2020 is the latest version on macOS, but it is a discarded version due to compatibility issues. The official latest version is ksh93u+, and the unofficial bug-fixed version is ksh93u+m.

This can be reproduced in the following way. If you remove `typeset`, it will work fine.

```diff
diff --git a/tetris b/tetris
index c08a360..ee04710 100755
--- a/tetris
+++ b/tetris
@@ -530,7 +530,7 @@ if (PATH=/dev/null; f() { local v; }; f) 2>/dev/null; then
 else
   localvar() {
     set -- "$1" "$*"
-    eval "function $1 { typeset${2#"$1"}; _$1 \"\$@\"; }"
+    eval "function $1 { _$1 \"\$@\"; }"
   }
 fi
```

Use `typeset` to reproduce it. (You may need to play with it for a while.) 

```diff
@@ -1587,10 +1587,10 @@ _redraw_playfield() {
 #   4 - rotation
 #   5 - cell content
 #   6 - mask with playfield
-localvar draw_piece posx posy type rotation content x y mask
-_draw_piece() {
+#localvar draw_piece posx posy type rotation content x y mask
+function draw_piece {
   # at first, we should save arguments.
-  posx="$1"; posy="$2"; type="$3"; rotation="$4"; content="$5"; mask="${6:-false}"
+  typeset posx="$1"; posy="$2"; type="$3"; rotation="$4"; content="$5"; mask="${6:-false}"

   # set minos coordinates.
   eval set -- \$piece_"$type"_minos_"$rotation"
```

I have an idea to implement a stack to store variables as a way to achieve local variables instead of `typeset`. But in my opinion, it's overdoing.

I think it is better to stop using `local` and `typeset` and use global variables carefully. The current code works with very little modification. I am going to create a PR for the proposed changes.

**Comment by ContentsViewer** [comment]
Thanks for your investigations.
Since Solaris 11 also uses ksh93, it is reproduced (the game behavior being slower and slower).

If this issue is fixed, the game will also work fine on Solaris 11 as well.
