### ISSUE TITLE
`local` is not available on POSIX sh

### ISSUE THREAD

**Issue by eggplants** [ContentsViewer/sh-tetris#7]
`local` is not available on POSIX sh.
So, if you want to improve compatibility, consider removing them.

**Comment by eggplants** [comment]
```shellsession
$ shellcheck -i SC3043 tetris

In tetris line 675:
  local x_test y_test x y lx ly field_cell
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 706:
  local color lx ly x y
  ^-------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 728:
  local x line_y="$1"
  ^------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 742:
  local x y yi completed_lines field_cell completed_lines_count action
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 837:
  local factor score_to_add lines_to_add actions_to_show i
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1051:
  local direction="$1" old_rotation new_rotation
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1074:
  local direction="$1" old_rotation new_rotation shift_x shift_y new_x new_y point
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1194:
  local x y yp field_cell
  ^---------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1221:
  local posx posy type rotation content lx ly x y mask
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1261:
  local color
  ^---------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1276:
  local color visible x y content
  ^-----------------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1308:
  local visible="$1" color
  ^----------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1332:
  local x1 x2 y1 y2 i x y
  ^---------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1367:
  local visible=${1:-$help_on} x y line
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1443:
  local x y i from cmd pid statement
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1545:
  local trigger_counter timestamp
  ^-----------------------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1596:
  local key a='' b='' esc_ch='1b' cmd
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.


In tetris line 1664:
  local cmd statement issued_time from
  ^-- SC3043 (warning): In POSIX sh, 'local' is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC3043 -- In POSIX sh, 'local' is undefined.

```

**Comment by ko1nksm** [comment]
Instead of removing `local`, we can increase the number of supported shells by using `typeset` together. I am working on ksh support locally. I will create a PR later.

**Comment by ko1nksm** [comment]
The explanation is in Japanese. Sorry :-P

単純に `local` を取り除くとグローバル変数になってしまいます。この問題に対処するにはいくつかの方法があります。

### 1. グローバル変数を名前がかぶらないように注意して使う

POSIX に完全に準拠することが出来ますが、変数名に気をつける必要があります。また再帰的に関数が呼び出される場合は注意が必要です。コードが増えてくるとメンテナンスが大変になると思いますが、sh-tetris の場合 ksh でもそれなりに動いているようなので、この方法でもそこまで大変ではないかもしれません。

### 2. 位置パラメータをローカル変数として使う

以下のようにして位置パラメータをローカル変数として使うテクニックがあります。

```sh
foo() {
    set -- "$1" "$2" "$IFS"
    IFS=:
    ...
    IFS=$3
}
```

POSIX に完全に準拠することが出来ますが、コードが複雑になる可能性があります。特に位置パラメータの数が固定でない場合は `eval` を駆使した分かりづらいコードになりがちで可読性が悪くなります。元のコードをかなり書き換えることになると思います。

### 3. サブシェル・コマンド置換を利用する

POSIX に完全に準拠することが出来ますが、グローバル変数とローカル変数が混在する場合に難しくなる可能性があります。また sh-tetris の場合は無視できないパフォーマンス低下が懸念されます。

### 4. `local` と `typeset` を併用する

今回実装したコードです。殆どのシェルでは `local` を使い、ksh では `typeset` を使います。

`local` と `typeset` のどちらも POSIX で標準化されているわけではなく、実装されていないシェルがありますが極めてマイナーなシェルだけです。

- posh - https://packages.debian.org/bullseye/posh
- pbosh - http://schilytools.sourceforge.net/bosh.html

ローカル変数をそのまま使えるため書き換えは最小限です。ただし世間では見かけないテクニックです。（少なくとも私はこれに類するテクニックを使っている例を見たことがない）

例えば以下のように書き換えます。ローカル変数は必ず関数内で初期化してから使用してください。動作に違いがあったはずです。

```sh
func() {
    local a=1 b=2 c
    ...
}

        ↓

localvar func a b c
_func() {
    a=1 b=2
    ...
}
```

これを実現する `localvar` 関数です。

```sh
if (PATH=/dev/null; f() { local v; }; f) 2>/dev/null; then
  localvar() {
    set -- "$1" "$*"
    eval "$1() { local${2#"$1"}; _$1 \"\$@\"; }"
  }
else
  localvar() {
    set -- "$1" "$*"
    eval "function $1 { typeset${2#"$1"}; _$1 \"\$@\"; }"
  }
fi
```

このあと、このテクニックを利用したコードのプルリクを作成します。マージするかどうかはおまかせします。気に入らなければ自由に閉じてください。

**Comment by ko1nksm** [comment]
I created the PR.

**Comment by ContentsViewer** [comment]
Thank you!
I'll check it, but may be some time.

**Comment by lubyagin** [comment]
See "Variable Naming Conventions" (StackOverflow), ... The OpenBSD developers typically define function-only variables using a leading underscore (examples can be found in /etc/netstart and /etc/rc): https://stackoverflow.com/a/75728815/966789

Here are some conventions one could follow to maintain scoped variables in POSIX-compatible shell scripts:

Variable	Description
VAR_NAME	environment variables
Var_Name	script constants (define using readonly when possible)
var_name	global variables
_func_var_name	local function variables
