### ISSUE TITLE
Does not lockdown when pieces are stacked on side

### ISSUE THREAD

**Issue by ko1nksm** [ContentsViewer/sh-tetris#84]
The next piece will not be generated.

<img width="500" src="https://user-images.githubusercontent.com/2453619/148624828-5f3bf7ca-acfc-4678-85df-fd56994cc83c.png">

**Comment by ContentsViewer** [comment]
It is reproduced on Ubuntu 18.04.
It seems to be something wrong with the lockdown from the right/left movement.

I'll fix it.

Thank you.
